### ISSUE TITLE
Improve overflow when lots of measurements of one intersection

### ISSUE THREAD

**Issue by jakecoppinger** [jakecoppinger/better-intersections#16]
<img width="627" alt="Screen Shot 2023-09-18 at 12 50 25" src="https://github.com/jakecoppinger/better-intersections/assets/10473201/e3c1db19-673c-4404-8ddc-76e986abbdce">

Open to ideas. Perhaps a horizontal scroll would be the go.

**Comment by Uzaif-Sheikh** [comment]
Hi @jakecoppinger , for marker popup I was wondering if we should only show the average time for green, flashing red, red and cycle length rather than showing all the observation and Notes. If someone wants to look at more detail for that point, they can go on 'view more stats about this intersection'?

Ultimately if there are more observation the popup will not look really ui friendly. But if showing all the observations is necessary I'll go ahead with horizontal scroll for the popup box.

**Comment by 17Ayaan28** [comment]
@jakecoppinger thoughts on this ? ^ - I'll take this up

**Comment by jakecoppinger** [comment]
Improved in https://github.com/jakecoppinger/better-intersections/pull/35
