### ISSUE TITLE
Passwordless email sign in to replace Google auth

### ISSUE THREAD

**Issue by jakecoppinger** [jakecoppinger/better-intersections#3]
Ideally users wouldn't be required to sign into their Google Account to them submit form timings.

A better UX for the form requires a custom form. I'm hesitant to implement a form without some sort of gating via email (or phone number) to prevent spam from a single individual.

Passwordless sign in would accomplish this, but would likely involve architecture this into a full stack app (rather than static). Any alternative ideas are welcome too!

**Comment by 17Ayaan28** [comment]
Hey Jake, I am taking this issue. Want to discuss this before I start coding -

We can build a multi step form (apparently multi-step discourages spam and is better UI) in better intersections to record data instead of using google forms. 

If we make use of passwordless sign in, we will know the email id of the person making a particular submission. That person can still make multiple submissions with the same email id but I assume the point is that we will be able to remove their submitted data in case we identify it to be spam. But we don't need a backend for this - we can just store an email along with the data on google sheets, right ?

Further, we can use Google Recaptcha (https://developers.google.com/recaptcha/intro), geo-fencing outside Aus/Syd(https://developers.google.com/location-context/geofencing), disallow links.

**Comment by jakecoppinger** [comment]
Hey Ayaan,

Thanks for starting to look at this. Really sorry but I'll take it over if that's alright - I'll deep dive on it this weekend.

Yep I agree, we likely won't require a backend - but we'll still need a way to verify emails. Otherwise someone could impersonate others easily. I'm hoping there is an API that can handle this (something like https://messagebird.com/ or sparkpost) and an npm module that handles the cookies and auth code. If not I could write this, but I've only used a backend before (eg. in https://github.com/gatho-party/gatho-website)
